org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.1
minecraft_version_range=[26.1.1]
neo_version=26.1.1.0-beta

mod_id=spittingimage
mod_name=Spitting Image
mod_license=ARR
mod_version=5v-26.1.1-neoforge
mod_group_id=mett.palemannie.spittingimage